### ISSUE TITLE
Learning more about IEEE Standards

### ISSUE THREAD

**Issue by thejourneydude** [drparadoxical/aeon-project-planning#2]
@drparadoxical Can you provide more information on the IEEE Standards? Specifically...

1. What projects have used these standards and what benefits were gained vs. using other systems like Agile? Can such a comparison to Agile be made or is IEEE something more?
2. Is there more friendly documentation written about IEEE standards? The documentation you uploaded is dense and rather confusing for the first-time reader. I myself have never heard of IEEE till now.

**Comment by firecrypt** [comment]
IEEE is one of those organizations that you interact with on a daily basis without knowing about it. Haha. They devolp a lot of standards that regulatory bodies end up adopting. 802.11 (wifi) is a great example. I think their standards make sense in heavily regulated areas (safety/health) but might be overkill for this. Having a publicly viewable Trello board might accomplish the same end goal: community visability. 

If you still think we need that much doc, I'm open to it, but it might slow us down.

**Comment by firecrypt** [comment]
IEEE Standards Association: http://standards.ieee.org/

**Comment by thejourneydude** [comment]
@firecrypt, Thanks for the clarification! 

Imo something like Trello works for me. It's simple, an easy barrier to entry, and it's something I think a lot of people are used to.

**Comment by drparadoxical** [comment]
Just now settling back in from pre-holiday preparations today, apologies for the delay gentlemen. Meeting you point for point respectively, accordingly. 

journey, IEEE Standards do not dictate design patterns or development practices per se, they are the guidelines and standards used by those who create Agile as a development practice. For example, IEEE Std. 1471, Recommended Practice for Architectural Description of Software-Intensive Systems, cares not whether it's adhered to when employing Agile, for it's a recommendation on how best to describe a system architecture. This leads to fire's first point nicely. 

fire, yes, if and when one attempts to adhere to the IEEE standards strictly, completely, nothing, and I mean nothing, gets done. A whole lot of paperwork, I suppose, but other than that, nothing. We will not be subjecting ourselves to such horseshit nonsense, we will simply be allowing the guidelines to help us maintain rigid structures when itemizing requirements, collapsing those into modularized units of work (arcs, milestones - essentially IEEE Std. 830 Best Practices for Software Requirements Specifications), and wrapping at least a thin layer of SOP around the work itself - in the form of a thorough enough project management plan (IEEE Std. 1049 Rec. Guidelines for SPMP). To be more specific, I'll be doing most of that, because we're going to be approaching this work a bit more methodically than you all are used to, I think. 

An example here and now as to why such rigidity and international guidelines and standards are so important and, while a bit bloated and cumbersome, keep us from walking into a handful of tickets/tasks, where it seems like things are going well and people are involved and work is being done, but no such requirements or tasks exist. 

I'll be going through all the tickets and requests and tasks here shortly in order to get back with all involved, because I'll not be telling everyone what to do and when to do it and what they're supposed to be doing and what they shouldn't have done - no sir, and not what I mean here with this comment. 

What I mean here with this comment, is that some standards and guidelines work is going to be done first, it adheres, somewhat strictly, to specific IEEE Standards  - specifically 830 and 1049, as running fast and loose, those rough drafts born from the 830 and 1049 Standards are bare minimum for a project's proper, reliable logistics/optics/efforts. Again, I'm biting this, and if I'm saying anything, its "team, please hold, we're preparing for attack, but holster, let's plan first, so when we fire, it's only once"

Also, fire, I can see about redacting corporate contracts and providing you with examples, but assure you, it's not just safety/health. If you want to sell a system to a city, for example, not a chance in hell without adherence to these standards, and that's just for the damn operations manual. In time, though, they become your bible, and it only takes use and practice and time to turn 6 binders of standards from something you fear and despise and see as unnecessary, to something you turn to when you're trying to keep unbounded madness and insane complexity on some sort of sane schedule or track. 

journey, as per your point at the end about Trello, I copy. Before we get into systems selection for internal use, though, let me get back to everyone here, keep the ball rolling, finish the intake documentation so the community knows a team has formed and we're apprised of the basics of what form it is we've taken here, and move onto the SPMP and SRS over the next few days. 

Smooth said he'd review the SPMP and SRS, and the reqs will also be publicly available, visible to all, so I strongly advise that, again, we holster weaponry for now, just for a few days, because there's some structure and rigidity I need to create for us all first. 

Of course, ignore me, do whatever you want. I'm not your damn father, and this isn't someone telling you what's best for you. If my fools rush in guns blazing and ignore everything I say, it simply means it's time I get foolish too. 

At the end of the day, we're here because we wanted to do this work. If you allow me to do so, I'll ensure it's done, correctly, quickly, with minimal effort, once. 

I suppose that's what I'm trying to say with all of this. 

I write white papers faster and far more often than you'd even believe, surprised no one has figured out who I am yet given all those damn publications, thus why it's hard for me to respond in anything less than a million words. My apologies, several times, in advance, for my loquacious bullshit nonsense, don't mean no harm by it. 

Onward.

**Comment by thejourneydude** [comment]
You had me at "I'll ensure it's done, correctly, quickly, with minimal effort, once."

**Comment by firecrypt** [comment]
@drparadoxical Sorry, I was generalizing what IEEE-SA does. I haven't used the IEEE software development standards before because my work [developed their own way of doing stuff](https://xkcd.com/927/), but I'm aware of them. I'll dive into them more this weekend. 

I'm in complete agreement: plan, then execute.

**Comment by drparadoxical** [comment]
Leaving this open until project planning is phased out, in the event anyone has any questions about the standards and how they're being used throughout the planning phase.

**Comment by drparadoxical** [comment]
Closing for now, will likely move to wiki pages once project completion reached and project cleanup and post-completion documentation is approached.
